export const createUser = (req, res) => {
    // ...existing code...
    // Logic to create a user
    // ...existing code...
};

export const createPost = (req, res) => {
    // ...existing code...
    // Logic to create a post
    // ...existing code...
};
